export { Interval } from "./interval"
export { Nothing, isAnything, isNothing } from "./nothing"
export { isNumber } from "./number"
export { isSet, union, intersection, difference } from "./set"
export { isString } from "./string"
