name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "14"]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: 38bbaa172c6d62c02a8cf2a4e77bdfda268b4c94012e4dd9f69a6a7e8f63bada
        with:
          coverageCommand: yarn coverage
